spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/issue_tracking_system_database
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

